function steps = bringupSteps()
%bringupSteps The guided bringup procedure, as data.
%
%   steps = tfp.gui.bringupSteps()
%
%   ONE declarative entry per section of docs/BRINGUP_GUIDE.md sections 1-7,
%   in the order they must be done. This is the script the guided wizard
%   reads out loud: what to do at the bench, what the software is about to
%   do, what a good result looks like, and what to change when it is not.
%
%   WHY THIS IS DATA AND NOT CODE. The wizard has to (a) show the whole
%   procedure before any of it has run, (b) know what is blocked by what,
%   and (c) explain a failure in the same words whether it happened in the
%   GUI or at the command line. A list of buttons with instructions buried
%   in their callbacks can do none of those. Keeping it declarative also
%   means the acceptance thresholds are all visible in one file and can be
%   diffed when someone changes one.
%
%   No graphics, no hardware, no arithmetic — tfp.gui.stepMetrics derives
%   the quantities the criteria test, and tfp.gui.stepVerdict applies them.
%   All three run under matlab -nodisplay and are covered by
%   tests/test_bringup_steps.m.
%
%   FIELDS OF ONE STEP
%     .id        char slug, stable — results and report sections key on it
%     .section   the docs/BRINGUP_GUIDE.md section number this implements
%     .title     one short line for the step rail
%     .purpose   one sentence: what this measures and why it must be done
%     .kind      'checklist' (operator confirms) | 'measure' (software acts)
%     .requires  step ids that must have passed first
%     .needs     device keys the session must have real, before it may run
%     .setup     cellstr — what to do PHYSICALLY, before pressing Proceed
%     .willDo    cellstr — what the software will do when you press Proceed
%     .hazard    char — the safety sentence for this step, '' if none
%     .checks    cellstr — checklist items ('checklist' steps only)
%     .method    CalibrationSession method to call ('measure' steps only)
%     .knobs     struct array of operator-settable options (see knob())
%     .saveKind  tfp.io.saveCalibration slug, '' for steps that save nothing
%     .criteria  struct array of acceptance tests (see crit())
%     .remedy    cellstr — what to change on the bench when it does not pass
%     .records   cellstr — the numbers to write on the record sheet (section 11)
%     .plot      recipe name the view renders; 'none' for checklist steps
%
%   See also tfp.gui.stepVerdict, tfp.gui.stepMetrics,
%   tfp.gui.CalibrationSession/runStep, docs/BRINGUP_GUIDE.md.

steps = emptyStep();

% =========================================================================
% Section 1 - prerequisites. Nothing here touches the rig; both steps exist
% because every downstream number is wrong in a way that still looks
% self-consistent if the bench is not what the handoff says it is.
% =========================================================================

s          = newStep('prereq_bench', '1', 'Bench prerequisites');
s.purpose  = ['Confirm the arm on the table is the arm the handoff describes. ' ...
              'Every scale constant downstream is computed for one specific ' ...
              'prescription, and a half-done lens swap looks self-consistent ' ...
              'while being wrong by a fixed factor.'];
s.kind     = 'checklist';
s.setup    = { ...
    'Nothing is powered for this step - it is a walk along the bench with the handoff open.'
    'Open docs/optics_handoff.md and read the "build_label" line at the top of the constants block.'
    'Check each lens seat against that label, not against memory.'};
s.checks   = { ...
    'Ra = 250 mm and Rb = 200 mm in the pre-grating relay (rev 5 moved Ra from 300 - check the SEAT, not just f7)'
    'f7 = 300 mm confirmed in its seat (bench-confirmed 2026-08-19)'
    'f6 = 80 mm confirmed installed (bench of record carried 150 mm - this is the swap the f7 confirmation did NOT cover)'
    'Grating incidence re-set to 43.7 deg in / 33.7 deg out (rev 5 re-angled it from 42.8/34.5)'
    '3D-SHOT zero-order block at I1 REMOVED (it shadows the middle of the merged field)'
    'DMD chip Scheimpflug tilt set - sign is OPPOSITE the old bring-up-arm instructions'
    'Half-wave plate + polarizer set for s-pol on the grating'
    'Beam expander identity recorded (custom 1.75x vs GBE02-B changes the dwell-correction table)'
    'Thin fluorescent film slide at the rig (lateral and z calibration)'
    'Thick fluorescent slab at the rig (section 7 burn/bleach verify)'};
s.remedy   = { ...
    'Any unchecked box stops the run here rather than propagating a silent scale error.'
    'If a lens differs from the handoff, do not adjust the software: change the model in the'
    'optics repo, regenerate docs/optics_handoff.md, and commit it here. The handoff is the'
    'authority and this repo reads it at runtime.'
    'The two-lens trap: Ra 300->250 and f7 250->300 are both ratios of 1.2 and they enter the'
    'scale inversely, so correcting only one leaves every internal consistency check passing'
    'and the groove scale wrong by 1.2x.'};
s.records  = {'build_label from the handoff constants block'
              'Beam expander identity (custom 1.75x or catalogue GBE)'};
steps(end+1) = s;

s          = newStep('prereq_software', '1', 'Software and device preflight');
s.purpose  = ['Interrogate every instrument this session will drive, and say ' ...
              'which ones answered. A device that is silently simulated is how ' ...
              'a session produces confident numbers about hardware that was ' ...
              'never there.'];
s.kind     = 'measure';
s.method   = 'preflight';
s.setup    = { ...
    'Repo cloned and up to date on all three PCs, with addpath(''src'') done in each MATLAB.'
    'msocket library on the path of all three (the msocketPath config keys).'
    'On the imaging PC, inside the ScanImage MATLAB: addpath(''<repo>/scripts/imaging_pc_setup'');'
    '  si_calib_helper  (port 3048 - the z ruler AND ScanImage control; set zstage.relay_port: 3048)'
    '  or si_motor_helper (port 3047 - the z ruler only). Run ONE: a MATLAB holds one accept loop.'
    'On the SLM PC: cd <repo>; addpath(''src''); addpath(''scripts/slm_pc_setup''); slm_server'
    'configs/real.yaml reviewed - slm.host, zstage, etl, threeD, laser.carbide_modulator_ao_channel.'};
s.willDo   = { ...
    'Ask the DMD, DAQ, camera and z ruler to identify themselves and answer a round trip.'
    'Report whether the CARBIDE modulator is wired, whether the PM100D driver is present,'
    'and whether the ScanImage link is configured.'
    'Name every device that fell back to a simulator.'};
s.criteria = [ ...
    crit('m.nFailed', 'Devices that failed to answer', '', 'eq', 0, 'fail', ...
         'A device that cannot be reached cannot be calibrated. Fix it before measuring.') ...
    crit('m.nUnexpectedlySimulated', 'Devices that fell back to a simulator', '', 'eq', 0, 'adjust', ...
         ['A device that was asked for by name and could not be built is now a simulator, and ' ...
          'nothing measured against it is a calibration. The MATLAB console carries the original ' ...
          'construction error, which is the real diagnosis.']) ...
    crit('m.nSimulatedRows', 'Devices declared simulated', '', 'eq', 0, 'warn', ...
         'Expected on a mock session, where the whole rig is simulated on purpose and says so.') ...
    crit('m.nPending', 'Devices not yet configured', '', 'eq', 0, 'warn', ...
         'Pending is not broken - it usually means the laser state has not been entered yet.')];
s.remedy   = { ...
    'Work the "What to do" column of the preflight table top to bottom; it names the fix per device.'
    'A simulated device is a construction failure that was caught and substituted - the warning in'
    'the MATLAB console carries the original error message, which is the real diagnosis.'};
s.plot     = 'preflight';
steps(end+1) = s;

% =========================================================================
% Section 2 - the SLM link. Before any light: this is a network handshake.
% =========================================================================

s          = newStep('slm_link', '2', 'SLM PC link');
s.purpose  = ['Prove the DAQ PC can drive the Meadowlark through the SLM PC ' ...
              'before anything depends on it. The DAQ PC never sends pixels - ' ...
              'it sends a small mask spec and the SLM PC recomputes identical ' ...
              'masks with the same engine.'];
s.kind     = 'measure';
s.method   = 'runSlmLinkCheck';
s.needs    = {'slm'};
s.setup    = { ...
    'Work through docs/blink-api-audit.md on the SLM PC first - the load-bearing question is'
    'whether this unit does onboard-sequence memory with external-trigger advance, which decides'
    'slm.trigger_mode (''ttl'' if yes, ''software'' permanently if no).'
    'Edit scripts/slm_pc_setup/slm_pc_config.m: port 3046, DLL / header / LUT paths.'
    'Leave dryRun = true for the first link test - no hardware is touched in dry run.'
    'Start the server and leave it running: slm_server (it listens until SHUTDOWN or Ctrl-C).'
    'Once the dry run passes, set dryRun = false, restart slm_server, and run this step again.'};
s.willDo   = { ...
    'Connect to the SLM PC on port 3046.'
    'Build the defocus system from the config and prepare a three-mask sequence (-20, 0, +20 um).'
    'Expect READY back, then blank the device and expect BLANK_OK.'
    'Leave the SLM blanked - a flat mask is the safe state.'};
s.criteria = [ ...
    crit('connected',  'msocket link to the SLM PC', '', 'isTrue', true, 'fail', ...
         'Without the link nothing axial can be calibrated or run.') ...
    crit('readyOk',    'READY handshake on a prepared sequence', '', 'isTrue', true, 'fail', ...
         'READY is the server confirming it recomputed the same masks from the spec.') ...
    crit('blankOk',    'BLANK acknowledged', '', 'isTrue', true, 'fail', ...
         'Blank is the walk-away state; if it does not work, the device cannot be left safe.') ...
    crit('dryRun',     'Server still in dryRun', '', 'isFalse', false, 'warn', ...
         'A dry run proves the protocol, not the upload. Repeat with dryRun = false before trusting it.')];
s.remedy   = { ...
    'tfp:hardware:MeadowlarkSLM:replyTimeout - slm_server is not running, slm.host is wrong, or a'
    'firewall is in the way. The server prints every command it receives, so look at its console first.'
    'tfp:hardware:BlinkSLM:sdkNotVendored - the Blink audit is not done. The server runs dry until'
    'the header is vendored in vendor/meadowlark/official/ and audited. Never invent a Blink'
    'function name to get past this.'
    'Record the decided trigger_mode in configs/real.yaml before moving on.'};
s.records  = {'slm.trigger_mode decided (ttl or software)'
              'Blink SDK version and DLL path'};
s.plot     = 'none';
steps(end+1) = s;

% =========================================================================
% Laser state. Not a section of its own in the guide, but nothing that puts
% light on the sample may run before it: the pulse-energy interlock is
% fail-closed on rep rate.
% =========================================================================

s          = newStep('laser_state', '0', 'Laser state');
s.purpose  = ['Tell the interlock what the laser is actually doing. Believing ' ...
              '100 kHz while the pulse picker sits at /100 understates pulse ' ...
              'energy a hundredfold, so every light-emitting step is blocked ' ...
              'until this is entered.'];
s.kind     = 'measure';
s.method   = 'applyLaserState';
s.setup    = { ...
    'Read the values off the CARBIDE control software on the Holo PC - do not recall them.'
    'Enter the FRONT-PANEL AVERAGE POWER if you can see it. That is a laser-plane number, so the'
    'interlock needs no arm-transmission assumption; without it the interlock scales a sample-plane'
    'power up by the unmeasured 0.182 and warns on every call.'
    'Note the pulse-picker division. This is the single most dangerous field on the form.'};
s.willDo   = { ...
    'Adopt the state, compute the effective rep rate, and stamp it into every calibration saved'
    'for the rest of this session.'
    'Enable the steps that emit light.'};
s.knobs    = [ ...
    knob('repRateKhz',          'Base rep rate',            100,  'kHz', 'CARBIDE base rate BEFORE the pulse picker.') ...
    knob('pulsePickerDivision', 'Pulse-picker division',      1,  '',    'A wrong division mis-scales every pulse-energy check.') ...
    knob('frontPanelPowerW',    'Front-panel average power',  0,  'W',   'PREFERRED interlock input. 0 = not entered.') ...
    knob('frontPanelSetpointNm','Front-panel setpoint',    1030,  'nm',  'Certificate s/n C264570 measures 1038; both are recorded.')];
s.criteria = [ ...
    crit('effectiveRepRateHz', 'Effective rep rate', 'Hz', 'gt', 0, 'fail', ...
         'The interlock divides average power by this to get pulse energy.') ...
    crit('m.hasFrontPanelPower', 'Front-panel power entered', '', 'isTrue', true, 'warn', ...
         'Without it every interlock call assumes the unmeasured 0.182 arm transmission and warns.')];
s.remedy   = { ...
    'If the front-panel power is unknown, the session still runs - it will warn'
    'tfp:util:assertPulseEnergySafe:armTransmissionAssumed on every light-emitting call.'
    'Measuring laser head -> sample transmission and recording laser.arm_transmission retires that warning.'};
s.plot     = 'none';
steps(end+1) = s;

% =========================================================================
% Section 3 - power. The first step that emits light.
% =========================================================================

s          = newStep('power_curve', '3', 'Volts to mW');
s.purpose  = ['Calibrate the CARBIDE modulator against the power meter so ' ...
              'every later step can ask for milliwatts instead of volts, and ' ...
              'so the interlock knows what a commanded voltage means.'];
s.kind     = 'measure';
s.method   = 'runPowerSweep';
s.requires = {'laser_state'};
s.needs    = {'laser', 'laserState'};
s.hazard   = ['This step ramps the modulator to the ceiling you authorise. ' ...
              'Consent is taken ONCE for the whole ramp - a dialog per step ' ...
              'would train you to click through them - but the hard interlock ' ...
              'still runs on every single step.'];
s.setup    = { ...
    'Wire the CARBIDE external modulator to its DAQ AO channel. Record terminal, cable, voltage'
    'range and POLARITY in docs/WIRING.md, then set laser.carbide_modulator_ao_channel.'
    'VERIFY ON A METER THAT 0 V MEANS OFF before the beam is connected. Every zero-on-error path'
    'in this software assumes it, including the BEAM OFF button.'
    'Put the Thorlabs PM100D head at the SAMPLE PLANE and set its wavelength to 1038 nm.'
    'Clear the beam path of anything that should not see full power.'};
s.willDo   = { ...
    'Ask once for the ramp ceiling, then step the modulator from Start to End.'
    'At each step: settle, average several meter readings, and record the standard deviation.'
    'Fit the curve, load it into the laser controller, and report where the working powers sit.'
    'Return the modulator to zero at the end.'};
s.knobs    = [ ...
    knob('vMin',        'Start',           0, 'V', 'Begin at zero so the 0 V = off check is real.') ...
    knob('vMax',        'End',             5, 'V', 'The ramp ceiling you will be asked to authorise.') ...
    knob('nSteps',      'Steps',          21, '',  'More steps resolve a non-linear modulator response.') ...
    knob('settleTimeS', 'Settle per step', 5, 's', 'The meter head is thermal; too short reads low and drifting.') ...
    knob('nAverages',   'Readings/step',   5, '',  'The spread across these is the error bar on the curve.')];
s.saveKind = 'power_curve';
s.criteria = [ ...
    crit('m.zeroIsOff',      'Power at 0 V is off',      '',  'isTrue', true, 'fail', ...
         ['The open safety question in CLAUDE.md, answered by measurement: if 0 V is not off, ' ...
          'every zero-on-error path drives the laser the WRONG WAY. Nothing else may run.']) ...
    crit('m.monotonic',      'Curve is monotonic',        '',  'isTrue', true, 'adjust', ...
         'A non-monotonic curve cannot be inverted, so voltsForMw would be ambiguous.') ...
    crit('m.maxPowerMw',     'Maximum power reached',     'mW','gt',  1,    'fail', ...
         'Essentially no power at the sample means the beam is blocked, misaligned, or the shutter is closed.') ...
    crit('m.worstStdFrac',   'Worst reading scatter',     '',  'lt',  0.05, 'warn', ...
         'Scatter over 5 percent of the reading usually means the settle time is too short.') ...
    crit('m.hasWorkingPoint','5 mW is inside the range',  '',  'isTrue', true, 'warn', ...
         '5 mW is the calibration working power for every later step; it must be on the dial.')];
s.remedy   = { ...
    'Power at 0 V not off: STOP. Check the modulator polarity on a meter and fix the wiring or the'
    'controller''s voltage_min before anything else. This is not a software setting to work around.'
    'No power at all: shutter closed, beam blocked, wrong AO terminal, or the modulator BNC is on'
    'the wrong input. The DAQ log shows the voltage that was actually commanded.'
    'Non-monotonic or noisy: increase Settle per step; the S350C head has a thermal time constant'
    'of seconds, not milliseconds.'};
s.records  = {'Maximum power at the sample (mW)'
              'Voltage that gives 5 mW (calibration working power)'
              'Voltage that gives 42 mW (the SLM alignment cap - know where it is on the dial)'};
s.plot     = 'powerCurve';
steps(end+1) = s;

% =========================================================================
% Section 4 - lateral calibration, four gated sub-steps.
% =========================================================================

s          = newStep('lateral_dmd_camera', '4a', 'DMD to camera affine');
s.purpose  = ['Fit the transform from DMD pixels to substage-camera pixels ' ...
              'by projecting a grid of spots and finding where each one lands. ' ...
              'This is the measurement that makes targeting possible at all.'];
s.kind     = 'measure';
s.method   = 'runDmdToCamera';
s.requires = {'power_curve'};
s.needs    = {'dmd', 'camera', 'laserState'};
s.hazard   = 'Single small spots at calibration power - far under every cap.';
s.setup    = { ...
    'Put the THIN fluorescent film slide on the stage.'
    'Turn on the substage Basler and focus it on the film. Use the Camera tab: raise exposure until'
    'the spot is bright, then back off until "Mark saturation" shows no red - a clipped plateau'
    'silently degrades every centroid.'
    'Capture a dark frame with the beam off (Camera tab) so the background pedestal is subtracted.'
    'If you are on the section 5 Option B sample mount: do NOT move XY from here until 4c is done.'};
s.willDo   = { ...
    'Project a grid of single spots across the usable patch, one at a time.'
    'Snap the camera at each, find the spot centroid, and least-squares fit a 2D affine.'
    'Report the residual per point, so a single bad point is visible rather than averaged away.'};
s.knobs    = [ ...
    knob('gridSize',     'Grid points per side', 5, '',  'Five per side is 25 points - enough to see structure in the residuals.') ...
    knob('spotRadiusPx', 'Spot radius',          8, 'px','Bigger is brighter and easier to centroid; smaller is more precise.') ...
    knob('powerMw',      'Power',                5, 'mW','The calibration working power.')];
s.criteria = [ ...
    crit('residualErrorPx',    'Affine residual (RMS)',   'camera px', 'lt', 1,  'adjust', ...
         'Under one camera pixel is the bar in the guide. Above it, the fit is describing something that moved.') ...
    crit('nCalibrationPoints', 'Points that fitted',      '',          'gt', 8,  'fail', ...
         'Too few surviving points and the affine is under-determined however small its residual looks.') ...
    crit('m.scaleAgreesWithHandoff', 'Scale matches the handoff', '',  'isTrue', true, 'warn', ...
         ['Guide section 4: disagreement of more than a few percent means something is installed ' ...
          'differently. The measurement is still the calibration - this is a pointer to the bench.'])];
s.remedy   = { ...
    'Residual over 1 px, scattered: the film is out of focus for the camera, or the exposure is'
    'clipping. Refocus, drop exposure until no red saturation pixels remain, recapture dark, retake.'
    'Residual over 1 px concentrated in a few points: those spots probably fell outside the'
    'illuminated patch, where the Gaussian is dim. Reduce the grid extent and retake.'
    'Scale off by a few percent: read the "What invalidates the calibration" table in CLAUDE.md.'
    'The periscope order is the highest-leverage single item - reversed, it moves scale by 0.562x.'};
s.records  = {'Fitted um/px on both axes, compared against handoff 2.3040 groove / 2.6528 dispersion'
              'Residual (camera px)'};
s.plot     = 'residuals';
steps(end+1) = s;

s          = newStep('lateral_scan_camera', '4b', 'ScanImage field to camera');
s.purpose  = ['Register the two-photon scan field against the same camera ' ...
              'frame, so the DMD and the imaging raster can be composed into ' ...
              'one coordinate system.'];
s.kind     = 'measure';
s.method   = 'runScanCrossRegister';
s.requires = {'lateral_dmd_camera'};
s.needs    = {'camera'};
s.setup    = { ...
    'Leave the film and the camera exactly as they were for 4a. Moving XY invalidates both fits and'
    'the composition cannot see that it happened.'
    'On the imaging PC put ScanImage in FOCUS mode with a NON-SQUARE pixel count, e.g. 512 x 256.'
    'The non-square count is not a preference: the rectangle the raster burns on the film has a long'
    'axis, and that long axis is what identifies the fast (resonant) axis.'
    'ScanImage cannot see DMD spots - it is a point scanner. The camera is what sees both.'};
s.willDo   = { ...
    'Snap the camera while the 2p beam rasters the film, and find the bright rectangle.'
    'Fit the scan-field to camera affine and compose it with 4a into dmdToScan.'
    'Leave the axis signs as NaN - a passive camera image cannot resolve them. That is 4c.'};
s.knobs    = [ ...
    knob('scanPixelsFast', 'ScanImage pixels/line', 512, 'px', 'Must differ from lines per frame.') ...
    knob('scanPixelsSlow', 'ScanImage lines/frame', 256, 'px', 'The short axis is the slow (galvo) axis.')];
s.criteria = [ ...
    crit('m.rectFound',       'Scan rectangle located',  '', 'isTrue', true, 'fail', ...
         'No rectangle means the raster is not on the film, not in focus, or the camera missed the frame.') ...
    crit('m.pixelsAreSquare', 'Pixel count is square',   '', 'isFalse', false, 'adjust', ...
         'A square frame leaves the fast axis unidentifiable, and the composition would be a coin flip.') ...
    crit('m.aspectPlausible', 'Rectangle aspect matches the pixel counts', '', 'isTrue', true, 'warn', ...
         'A rectangle whose aspect disagrees with what ScanImage was told usually means the zoom changed.')];
s.remedy   = { ...
    'No rectangle: check ScanImage really is in Focus and not idle; raise PMT gain or the 2p power'
    'until the film glows; make sure the camera exposure is long enough to catch a whole frame.'
    'Square pixel count: change it in ScanImage and retake. This step cannot be fixed afterwards.'};
s.plot     = 'scanRect';
steps(end+1) = s;

s          = newStep('lateral_signs', '4c', 'Axis signs (mandatory)');
s.purpose  = ['Resolve the two axis signs that a passive camera image ' ...
              'physically cannot show. The resonant scanner sweeps ' ...
              'symmetrically, so a centred scan does not reveal which way ' ...
              'either axis runs.'];
s.kind     = 'measure';
s.method   = 'runVerifySigns';
s.requires = {'lateral_scan_camera'};
s.needs    = {'dmd'};
s.setup    = { ...
    'Keep ScanImage up and ready to accept a small mROI at a commanded position.'
    'Still do not move the stage in XY.'
    'You will be asked up to four questions - one per sign combination. Usually two settle it.'};
s.willDo   = { ...
    'Project one DMD spot and predict where it should appear in scan-field coordinates.'
    'Show you that predicted mROI centre; you command it in ScanImage and answer whether the spot'
    'is centred in it.'
    'On the first yes, fold the confirmed signs into dmdToScan and stop asking.'};
s.criteria = [ ...
    crit('scanVerified',        'Signs confirmed on the bench', '', 'isTrue', true, 'fail', ...
         'Unverified signs are a 1-in-4 chance of stimulating a mirror-image location. The guide calls this mandatory.') ...
    crit('m.signsResolved',     'Both signs are +1 or -1',      '', 'isTrue', true, 'fail', ...
         'A NaN sign means the loop exhausted its combinations without a yes.')];
s.remedy   = { ...
    'All four combinations rejected: the problem is upstream of the signs. Re-run 4a and check its'
    'residual, then 4b and check the rectangle really was the raster and not a reflection.'
    'Write the confirmed signs into the rig config so the next session starts from them.'};
s.records  = {'scan_fast_axis_sign and scan_slow_axis_sign (write both into configs/real.yaml)'};
s.plot     = 'none';
steps(end+1) = s;

s          = newStep('lateral_persist', '4d', 'Compose and save');
s.purpose  = ['Compose the two affines into the DMD to scan-field transform ' ...
              'and persist it with full provenance, so the next session starts ' ...
              'from a calibration rather than from a guess.'];
s.kind     = 'measure';
s.method   = 'composeLateral';
s.requires = {'lateral_signs'};
s.setup    = {'Nothing physical. This step is bookkeeping, and it is where the tripwire fires.'};
s.willDo   = { ...
    'Compose dmdToScan = inv(scanToCam) * dmdToCam.'
    'Compare the stage positions stamped on both fits, and warn if XY moved between them.'
    'Stamp laser state, git hash, config snapshot and camera settings onto the result and save it.'};
s.saveKind = 'dmd_affine';
s.criteria = [ ...
    crit('m.stagePositionConsistent', 'Stage did not move between 4a and 4b', '', 'isTrue', true, 'adjust', ...
         ['Both affines are anchored to the camera frame. An XY move translates BOTH and the ' ...
          'composition cannot see it - which is exactly why the position is stamped on each fit.']) ...
    crit('m.hasAffine',               'dmdToScan affine present',             '', 'isTrue', true, 'fail', ...
         'Nothing to save otherwise.')];
s.remedy   = { ...
    'Stage moved: re-run 4a and 4b without touching XY in between, then 4c again.'
    'After any deliberate XY move later (fresh film, burn-grid tiling), at minimum re-run the 4c'
    'verify before trusting targeting.'};
s.plot     = 'none';
steps(end+1) = s;

% =========================================================================
% Section 4.5 - the depth plane. New, and the one measurement nothing in the
% repo made before.
% =========================================================================

s          = newStep('field_tilt', '4.5', 'Field tilt (depth plane)');
s.purpose  = ['Measure how far the plane of best excitation tilts across the ' ...
              'field. Temporal focusing disperses the beam, so that plane is ' ...
              'tilted rather than flat, and the walk across the patch is ' ...
              'comparable to one axial FWHM - targets at opposite edges are ' ...
              'genuinely not in the same plane.'];
s.kind     = 'measure';
s.method   = 'runFieldTilt';
s.requires = {'lateral_dmd_camera'};
s.needs    = {'dmd', 'camera', 'zstage', 'laserState'};
s.hazard   = 'One small spot at a time at 5 mW. The z ruler moves the objective between sweeps.';
s.setup    = { ...
    'Thin fluorescent film still on the stage, camera still focused on it.'
    'The z ruler must be live. On the default objective mount that means si_motor_helper is running'
    'in the ScanImage MATLAB on the imaging PC (port 3047) - check the Preflight row.'
    'Make sure the objective has room to travel the search range in both directions.'};
s.willDo   = { ...
    'Project a spot at each of N field positions arranged in a ring inside the patch.'
    'At each position, sweep the objective through focus and find the z where the spot is sharpest.'
    'Fit z = a * x_disp + b * y_groove + c, using the 45 degree clocking mapping.'
    'Report the gradient, the walk across the full patch, and a proposed sign.'};
s.knobs    = [ ...
    knob('nRing',         'Points per ring',  8, '',  'More points tighten the fit; each one costs a full through-focus sweep.') ...
    knob('zSearchHalfUm', 'Search half-range',30, 'um','Must exceed the expected walk or focus clamps at the window edge.') ...
    knob('zStepUm',       'Step',              5, 'um','Finer resolves the focus peak better; 5 um is a good start.') ...
    knob('powerMw',       'Power',             5, 'mW','')];
s.saveKind = 'field_tilt';
s.criteria = [ ...
    crit('fit.r2',              'Plane fit r-squared',              '',      'gt', 0.98, 'fail', ...
         'The guide''s bar. A poor fit means the focus metric was not tracking real focus.') ...
    crit('m.nFocusAtEdge',      'Points clamped at a window edge',  '',      'eq', 0,    'fail', ...
         ['A clamped point biases the gradient toward zero - the very quantity being measured. ' ...
          'These points are excluded and flagged rather than quietly averaged in.']) ...
    crit('m.grooveFraction',    'Groove gradient vs dispersion',    '',      'lt', 0.3,  'adjust', ...
         ['Diagnostic, not merely disappointing: a large groove component means the tilt is not ' ...
          'along the dispersion axis at all, which points at a wrong 45 degree handedness or a ' ...
          'mis-clocked chip.']) ...
    crit('sanity.gradientInBand','Gradient inside the handoff band','',      'isTrue', true, 'warn', ...
         'Warns, never fails: the measurement is the truth and the handoff is design intent.') ...
    crit('sanity.walkInBand',   'Walk inside the handoff band',     '',      'isTrue', true, 'warn', ...
         'Same rule. Compare against the handoff''s 34.9 um across the patch.')];
s.remedy   = { ...
    'Points clamped at the window edge (tfp:calibration:measureFieldTilt:focusAtWindowEdge):'
    'widen Search half-range and retake. This is the most common failure and it is not subtle.'
    'Sweep finds no spot at all: film out of range, exposure too low, or the window missed focus.'
    'Widen the range, check the sweep threshold fraction, and make sure a dark frame is captured.'
    'Large groove gradient: this is a bench finding. Check the chip clocking and which diagonal the'
    'grating actually disperses along before re-measuring.'
    'Gradient outside the handoff band: not a failure. Record it, and check the bench prescription'
    'against the handoff build_label - the numbers move when lenses do.'};
s.records  = {'Fitted gradient a (um/um) along dispersion'
              'Walk across the full patch (um), against the handoff 34.9 um'
              'depthGradientSign - a PROPOSAL, pending the section 7.4 burn row'};
s.plot     = 'tilt';
steps(end+1) = s;

% =========================================================================
% Section 5 - the z ruler. Everything axial is measured against this one axis.
% =========================================================================

s          = newStep('z_ruler', '5', 'Z ruler check');
s.purpose  = ['Prove the one z axis that both axial calibrations will be ' ...
              'measured against. Everything axial - SLM defocus and ETL planes ' ...
              'alike - goes on this ruler so the composition is a direct ' ...
              'substitution rather than a conversion.'];
s.kind     = 'measure';
s.method   = 'runZRulerCheck';
s.requires = {'prereq_software'};
s.needs    = {'zstage'};
s.setup    = { ...
    'Decide the mount and record it in zstage.mount:'
    '  objective (DEFAULT) - the rig MP-285 moves the Sutter MOM. Backend relay needs'
    '  si_motor_helper running on the imaging PC; backend mp285 needs the switch box flipped'
    '  toward the DAQ PC and docs/mp285-protocol-audit.md item 1 (usteps per um) done first.'
    '  sample - a spare MP-285 carries camera and slide as one rigid unit. Removes a camera-defocus'
    '  bias from the section 6a slope and keeps calibration DAQ-PC-local.'
    'Have the film in view so you can SEE which way focus moves when the stage does.'};
s.willDo   = { ...
    'Read the position, command a small relative move, read back, and return to the start.'
    'Report the round-trip error and the mount and direction sign currently configured.'
    'Ask you to confirm which way focus actually moved - the software cannot see this.'};
s.knobs    = [ ...
    knob('testMoveUm', 'Test move', 10, 'um', 'Large enough to see, small enough to be safe.')];
s.criteria = [ ...
    crit('roundTripErrUm',       'Round-trip error',            'um', 'lt', 0.5, 'fail', ...
         'The guide''s bar. Backlash or a wrong usteps-per-um shows up here first.') ...
    crit('m.directionConfirmed', 'Plus z moves focus DEEPER',   '',   'isTrue', true, 'adjust', ...
         ['The ZStage contract. calibrateSlmDefocus compares the ABSOLUTE slope, so it will not ' ...
          'catch an inverted ruler for you - this step is the only place that does.']) ...
    crit('m.xyGateCorrect',      'XY moves gated to the sample mount', '', 'isTrue', true, 'warn', ...
         'On the objective mount a commanded XY move would translate the objective, so it throws.')];
s.remedy   = { ...
    'Round-trip error too large: check usteps_per_um for THIS unit (audit item 1 - it scales every'
    'z-calibration), and whether the move is completing before the position is read back.'
    'Focus moved the wrong way: set zstage.direction_sign to -1 and note it in'
    'docs/mp285-protocol-audit.md. The expected sign DIFFERS BY MOUNT, so do not copy the other rig''s.'
    'On the sample mount, also finish audit items 7 (XY framing) and 8 (payload, sag, camera-to-film'
    'focus invariance) before trusting this mount.'};
s.records  = {'zstage.mount and zstage.direction_sign, noted in the MP-285 audit doc'
              'Round-trip error (um)'};
s.plot     = 'none';
steps(end+1) = s;

% =========================================================================
% Section 6 - z calibration, the indirect (primary) method.
% =========================================================================

s          = newStep('z_slm_defocus', '6a', 'SLM defocus to microns');
s.purpose  = ['Turn SLM defocus commands into physical microns. The command ' ...
              'is defined in sample-plane microns by the mask formula, so a ' ...
              'correct system fits a slope near 1 - and the distance from 1 is ' ...
              'the honest measure of how well the optics model matches the bench.'];
s.kind     = 'measure';
s.method   = 'runSlmDefocus';
s.requires = {'z_ruler', 'slm_link'};
s.needs    = {'dmd', 'camera', 'zstage', 'slm', 'laserState'};
s.hazard   = ['One small spot at 5 mW - far under every cap. The SLM alignment ' ...
              'cap only binds for near-uniform patterns.'];
s.setup    = { ...
    'Thin fluorescent film on the stage; camera focused on it.'
    'slm_server running on the SLM PC with dryRun = false - a dry run cannot move focus.'
    'Set config.slm.m_relay to your best value from the optics model. There is no handoff key for'
    'it yet, so it is marked VERIFY; a wrong value shows up as the fitted slope missing 1.0.'
    'Confirm objective.name matches the objective actually installed - repeat this step per objective.'};
s.willDo   = { ...
    'For each commanded defocus: advance the SLM, sweep the objective through focus, and find the'
    'stage z where the spot on the film is sharpest.'
    'Fit zPhys = slope * dzCmd + intercept.'};
s.knobs    = [ ...
    knob('dzMaxUm',       'Command range (plus/minus)', 100, 'um', 'The fit is only as good as its lever arm.') ...
    knob('dzStepUm',      'Command step',                25, 'um', '') ...
    knob('zSearchHalfUm', 'Focus search half-range',     30, 'um', 'Around the EXPECTED focus for each command.') ...
    knob('zStepUm',       'Focus step',                   5, 'um', '') ...
    knob('powerMw',       'Power',                        5, 'mW','')];
s.saveKind = 'slm_defocus';
s.criteria = [ ...
    crit('fit.r2',            'Linear fit r-squared',   '',      'gt', 0.98, 'fail', ...
         'The guide''s bar. Below it the through-focus sweeps were not finding real focus.') ...
    crit('m.slopeAbsError',   'Distance of |slope| from 1', '',  'lt', 0.3,  'warn', ...
         ['Warn, not fail: THE FIT IS THE CALIBRATION. A slope far from 1 means m_relay, the ' ...
          'objective or the immersion disagree with the bench - fix the config for interpretability, ' ...
          'but the fitted slope is what gets used downstream.']) ...
    crit('m.nDefocusPoints',  'Defocus commands fitted', '',     'gt', 4,    'fail', ...
         'Too few points and the slope is not a measurement.')];
s.remedy   = { ...
    'Fitted slope far from 1: slm.m_relay is the first suspect (it enters quadratically), then'
    'objective.name, then immersion mismatch. Appendix A of the guide lists these in order.'
    'A sweep found no spot (tooFewPoints): widen the focus search half-range, check the sweep'
    'threshold fraction (default 0.3), and add a dark frame - defocused spots are dim.'
    'Poor r-squared with good individual sweeps usually means the SLM is not actually changing:'
    'confirm dryRun is false on the server and that READY came back for the whole sequence.'};
s.records  = {'Fitted slope (um per command um) and r-squared'
              'Objective the fit belongs to - it is per-objective'};
s.plot     = 'zfit';
steps(end+1) = s;

s          = newStep('z_etl_planes', '6b', 'ETL planes to microns');
s.purpose  = ['Put each imaging plane on the same ruler. ScanImage''s micron ' ...
              'scale for the ETL is not trusted, so each plane''s depth is ' ...
              'measured as the objective position where that plane sees the ' ...
              'film brightest.'];
s.kind     = 'measure';
s.method   = 'runEtlPlanes';
s.requires = {'z_ruler'};
s.needs    = {'zstage'};
s.setup    = { ...
    'Same thin fluorescent film, undisturbed.'
    'On the imaging PC: configure the REAL experiment''s fastZ stack - the plane count and spacing'
    'you will actually use - and confirm with probe_scanimage_config(''3d'').'
    'Leave ScanImage free-running that volume.'
    'Decide how plane brightness reaches this session: live per-plane means over the helper socket,'
    'or the offline route where you grab one small stack per z step and a wrapper reads the means.'
    'The offline route is slower and needs zero new plumbing on day one.'};
s.willDo   = { ...
    'Step the objective through a range of z positions.'
    'After each step, read the mean brightness of every imaging plane.'
    'Each plane peaks when the film sits at that plane''s focal depth; fit the peak per plane.'};
s.knobs    = [ ...
    knob('zRangeUm', 'Sweep range (plus/minus)', 40, 'um', 'Must cover all planes plus margin.') ...
    knob('zStepUm',  'Step',                      2, 'um', 'Finer than the section 6a sweep - these peaks are broad.')];
s.saveKind = 'etl_planes';
s.criteria = [ ...
    crit('m.nPlanesFitted',   'Planes with a located peak', '',   'gt', 1,    'fail', ...
         'A plane whose brightness never peaked was never in range.') ...
    crit('m.planesMonotonic', 'Plane depths increase in order','', 'isTrue', true, 'adjust', ...
         'Out-of-order depths mean the plane indexing is reversed relative to ScanImage''s.') ...
    crit('m.spacingMatchesConfig','Spacing matches what ScanImage was set to','','isTrue', true, 'warn', ...
         'A mismatch is informative: it is exactly the ETL micron scale this step exists to distrust.')];
s.remedy   = { ...
    'A plane never peaked: widen the sweep range, or check that ScanImage really is running the'
    'multi-plane stack (numSlices > 1) rather than a single plane.'
    'Depths out of order: the plane interleave is reversed. Check the stack order in ScanImage'
    'before assuming the measurement is wrong.'};
s.records  = {'Plane depths (um) - compare the spacing against what you set in ScanImage'};
s.plot     = 'planes';
steps(end+1) = s;

s          = newStep('z_compose', '6c', 'Compose the z calibration');
s.purpose  = ['Cross-register SLM defocus commands with imaging planes. Both ' ...
              'were measured on the same ruler, so this is a substitution, not ' ...
              'a conversion - which is the whole reason for insisting on one axis.'];
s.kind     = 'measure';
s.method   = 'composeZ';
s.requires = {'z_slm_defocus', 'z_etl_planes'};
s.setup    = {'Nothing physical.'};
s.willDo   = { ...
    'Compute the SLM command that focuses stimulation at each imaging plane.'
    'Check both inputs came from the same ruler and refuse to compose across a degenerate slope.'
    'Save the tag that gets stamped onto ROIs arriving with a plane index.'};
s.saveKind = 'z_composed';
s.criteria = [ ...
    crit('m.rulerMatches',   'Both fits used the same z ruler', '', 'isTrue', true, 'fail', ...
         'The composition assumes ONE common axis. Two rulers make the substitution meaningless.') ...
    crit('m.commandsInRange','Every plane needs a reachable command', '', 'isTrue', true, 'adjust', ...
         'A plane that needs more defocus than the SLM has range cannot be stimulated at.')];
s.remedy   = { ...
    'Ruler mismatch: re-measure 6a and 6b on the same axis. Do not paper over this.'
    'Commands out of range: reduce the imaging stack''s depth span, or accept that the outer planes'
    'are imaging-only. The remote focus range from the handoff is 908 um, but the usable span is'
    'set by where the fit stays linear.'};
s.records  = {'dzCmdForPlane - the SLM command per imaging plane'};
s.plot     = 'zcompose';
steps(end+1) = s;

% =========================================================================
% Section 7 - the direct verify, and the one number the indirect route
% cannot produce.
% =========================================================================

s          = newStep('verify_marks', '7', 'Burn/bleach verify');
s.purpose  = ['Cross-check the indirect z calibration by physically marking ' ...
              'the sample at known defocus commands and finding those marks in ' ...
              'an imaging stack. Independent of every assumption section 6 made.'];
s.kind     = 'measure';
s.method   = 'runMarkAndVerify';
s.requires = {'z_compose', 'lateral_persist'};
s.needs    = {'dmd', 'slm', 'daq', 'laserState'};
s.hazard   = ['Burn mode runs 50 mW for half a second per mark - the highest ' ...
              'power in the whole procedure, and the hardware-risk direction. ' ...
              'It is a single small spot, so it stays far under the pupil caps, ' ...
              'but choose the mode deliberately.'];
s.setup    = { ...
    'Swap the thin film for the THICK fluorescent slab. A film cannot hold marks at multiple depths,'
    'so this cross-check is slab-only whichever mount you are on.'
    'Choose the mode: burn first (short, high power); fall back to bleach (long dwell, moderate'
    'power) if no mark forms. Whether the DMD arm reaches burn threshold is an open question.'
    'After the marks are made you will acquire a stack on the imaging PC and bring the pixel data'
    'back to this PC as an array, frames plane-interleaved.'};
s.willDo   = { ...
    'Project one small spot per defocus command onto the slab and dwell, so the LATERAL GRID'
    'POSITION encodes which command made each mark - no bookkeeping ambiguity later.'
    'Lay that grid along the GROOVE diagonal, where the excitation plane is not tilted. Along the'
    'dispersion diagonal the tilt would add a depth offset growing with the same coordinate that'
    'encodes defocus, and the two would be inseparable.'
    'Wait for you to acquire the stack and load it.'
    'Find each mark, report which plane it is darkest in, and compare that against what the'
    'composed calibration predicted.'};
s.knobs    = [ ...
    knob('dzMaxUm',    'Mark defocus range (plus/minus)', 40, 'um', '') ...
    knob('dzStepUm',   'Defocus step',                    20, 'um', '') ...
    knob('gridStepPx', 'Mark spacing',                   100, 'px', ...
        ['Far enough apart that a defocused mark cannot be confused with its neighbour, ' ...
         'close enough that the whole grid stays inside BOTH the illuminated patch ' ...
         '(half-span must be under the patch radius) and the imaging field of view. ' ...
         'markFluorescentSlab''s own default of 120 overruns the patch at five marks.']) ...
    knob('powerMw',    'Power',                           50, 'mW', 'Burn default. Bleach uses 10 mW.') ...
    knob('dwellS',     'Dwell per mark',                 0.5, 's',  'Burn default. Bleach uses 30 s.')];
s.criteria = [ ...
    crit('m.allMarksInField', 'Every mark was inside the imaging field', '', 'isTrue', true, 'adjust', ...
         ['Checked separately from agreement, because a mark the imaging never saw still reports a ' ...
          'plane. An unimaged mark is a framing problem: the grid is wider than the raster.']) ...
    crit('pass',            'Every mark agrees with the prediction', '', 'isTrue', true, 'adjust', ...
         'Pass means each mark''s darkest plane is the plane the indirect calibration predicted.') ...
    crit('m.agreeFraction', 'Fraction of marks agreeing',            '', 'gt', 0.99, 'adjust', ...
         'Reported separately so a single disagreeing mark is visible rather than just a red flag.')];
s.remedy   = { ...
    'Marks outside the imaging field: the grid spans more of the DMD field than ScanImage images.'
    'Reduce Mark spacing, or zoom ScanImage out over the marked region, and retake.'
    'A tfp:util:assertPatternInPatch warning during marking means the grid also left the'
    'ILLUMINATED patch, which is unverified territory rather than merely dimmer. Reduce Mark'
    'spacing until the half-span is inside the patch radius.'
    'Disagreement suspects, in the order the guide lists them: m_relay sign, ETL plane order,'
    'stack interleave. All three produce a systematic offset rather than scatter.'
    'No marks formed at all in burn mode: switch to bleach mode (10 mW, 30 s dwell) and retake.'
    'That is the expected outcome if the DMD arm does not reach burn threshold, not a failure.'};
s.records  = {'Indirect vs direct agreement (marks agreeing / total)'};
s.plot     = 'marks';
steps(end+1) = s;

s          = newStep('verify_tilt_sign', '7.4', 'Tilt sign');
s.purpose  = ['Settle the one number the indirect method cannot produce: the ' ...
              'SIGN of the depth gradient. Magnitude always comes from the ' ...
              'handoff at runtime; only the sign is yours to measure.'];
s.kind     = 'measure';
s.method   = 'runTiltSign';
s.requires = {'verify_marks', 'field_tilt'};
s.needs    = {'dmd', 'laserState'};
s.hazard   = 'Same marking power as the previous step.';
s.setup    = { ...
    'Slab still in place.'
    'You will mark a ROW of spots at zero defocus, spanning the dispersion diagonal - the chip''s'
    '(1,1) direction. Because the excitation plane is tilted, those marks land at progressively'
    'different depths even though every command was the same.'
    'Acquire an imaging stack over that row and load it here.'};
s.willDo   = { ...
    'Mark a row along the dispersion diagonal at zero commanded defocus.'
    'Find which plane each mark is darkest in, and read the DIRECTION of the march across planes.'
    'That direction is the sign. Compare it against the proposal the field-tilt step made.'};
s.knobs    = [ ...
    knob('nMarks',     'Marks along the diagonal', 5,   '',   'Enough to see a monotonic march, not just two points.') ...
    knob('gridStepPx', 'Spacing along the diagonal', 100, 'px', ...
        ['The row has to span enough of the field for the tilt to carry the marks across a ' ...
         'plane boundary, WITHOUT any mark leaving the illuminated patch. Half-span is ' ...
         'gridStepPx * (marks - 1) / 2 and must stay under the patch radius.']) ...
    knob('powerMw',    'Power',                    50,  'mW', '') ...
    knob('dwellS',     'Dwell per mark',          0.5,  's',  '')];
s.criteria = [ ...
    crit('m.marchMonotonic',  'Marks march monotonically across planes', '', 'isTrue', true, 'fail', ...
         'A non-monotonic march is not a sign measurement - the row probably did not span enough depth.') ...
    crit('m.signAgreesWithTilt','Sign agrees with the field-tilt proposal','', 'isTrue', true, 'warn', ...
         ['If the two agree, that is a much cheaper confirmation than the burn route. If they ' ...
          'disagree, THIS one wins - the field-tilt sign was always a proposal.'])];
s.remedy   = { ...
    'Non-monotonic march: spread the row further along the diagonal so the depth span is larger'
    'than one plane spacing, and retake - but not past the patch radius, or the outer marks are'
    'made in unverified field angles (tfp:util:assertPatternInPatch says so during marking).'
    'If the row cannot both stay inside the patch and cross a plane, reduce the ETL plane'
    'spacing in ScanImage instead and re-run sections 6b and 6c.'
    'Write the confirmed sign into threeD.depth_gradient_sign in configs/real.yaml. Only the sign -'
    'the magnitude is read from the handoff at runtime and must not be pasted into the config.'};
s.records  = {'threeD.depth_gradient_sign (plus or minus 1), written into configs/real.yaml'};
s.plot     = 'marks';
steps(end+1) = s;

end

% ===========================================================================
% Builders. Local so the registry above reads as a table rather than as
% struct() calls with cell-wrapping noise.
% ===========================================================================

function s = emptyStep()
%emptyStep A 0x0 struct array with exactly the step fields, so appending is
%   always shape-safe and a typo in a field name fails loudly.
s = struct('id', {}, 'section', {}, 'title', {}, 'purpose', {}, 'kind', {}, ...
    'requires', {}, 'needs', {}, 'setup', {}, 'willDo', {}, 'hazard', {}, ...
    'checks', {}, 'method', {}, 'knobs', {}, 'saveKind', {}, 'criteria', {}, ...
    'remedy', {}, 'records', {}, 'plot', {});
end

function s = newStep(id, section, title)
s = struct('id', id, 'section', section, 'title', title, 'purpose', '', ...
    'kind', 'measure', 'requires', {{}}, 'needs', {{}}, 'setup', {{}}, ...
    'willDo', {{}}, 'hazard', '', 'checks', {{}}, 'method', '', ...
    'knobs', emptyKnob(), 'saveKind', '', 'criteria', emptyCrit(), ...
    'remedy', {{}}, 'records', {{}}, 'plot', 'none');
end

function k = emptyKnob()
k = struct('name', {}, 'label', {}, 'default', {}, 'unit', {}, 'hint', {});
end

function k = knob(name, label, default, unit, hint)
%knob One operator-settable option for a step.
k = struct('name', name, 'label', label, 'default', default, ...
    'unit', unit, 'hint', hint);
end

function c = emptyCrit()
c = struct('field', {}, 'label', {}, 'unit', {}, 'test', {}, 'value', {}, ...
    'severity', {}, 'why', {});
end

function c = crit(field, label, unit, test, value, severity, why)
%crit One acceptance test on a step's result.
%
%   field    dotted path into the result struct; a leading 'm.' reaches the
%            derived metrics from tfp.gui.stepMetrics.
%   test     'lt' | 'gt' | 'le' | 'ge' | 'eq' | 'isTrue' | 'isFalse'
%   severity 'fail'   the measurement did not work - retake it
%            'adjust' something PHYSICAL is wrong - change it, then retake
%            'warn'   outside a design band, but the measurement is the truth
%            'info'   reported, never gates anything
%   why      one or two sentences, shown next to the number in the report.
c = struct('field', field, 'label', label, 'unit', unit, 'test', test, ...
    'value', value, 'severity', severity, 'why', why);
end
