function [curve, truth] = powerMeterSweepSingle_mock(options)
%powerMeterSweepSingle_mock Run the REAL CARBIDE sweep against a synthetic meter.
%
%   [curve, truth] = tfp.calibration.powerMeterSweepSingle_mock()
%   [curve, truth] = tfp.calibration.powerMeterSweepSingle_mock(options)
%
%   Unlike the older powerMeterSweep_mock — which re-implemented the sweep's
%   arithmetic and therefore tested nothing that runs at the bench — this
%   drives tfp.calibration.powerMeterSweepSingle itself, through a real
%   tfp.hardware.LaserPowerController and a real tfp.hardware.MockDAQ, with
%   only the power meter replaced by tfp.sim.SyntheticPowerMeter.
%
%   options:
%     .voltageSteps   default linspace(0, 5, 11)
%     .maxMw          synthetic meter ceiling (default 50)
%     .noiseMw        synthetic read noise (default 0.005)
%     .confirmFcn     default @(spec) true; pass @(spec) false to exercise the
%                     declined path
%     .laserState     default 100 kHz, /1, 8.5 W front panel
%     .patterns       default a single small spot on a 100x100 chip
%
%   truth carries the synthetic response so a test can check recovery:
%     .responseFcn .voltageSteps .expectedMw .aoChannel .daq .laser .meter

if nargin < 1 || isempty(options), options = struct(); end

voltageSteps = tfp.util.configField(options, 'voltageSteps', linspace(0, 5, 11));
maxMw        = tfp.util.configField(options, 'maxMw',   50);
noiseMw      = tfp.util.configField(options, 'noiseMw', 0.005);
confirmFcn   = tfp.util.configField(options, 'confirmFcn', @(spec) true);
laserState   = tfp.util.configField(options, 'laserState', ...
    struct('repRateKhz', 100, 'pulsePickerDivision', 1, 'frontPanelPowerW', 8.5));

patterns = tfp.util.configField(options, 'patterns', []);
if isempty(patterns)
    patterns = false(100, 100);
    patterns(48:52, 48:52) = true;   % a sparse spot, as a real step would light
end

aoChannel = 'ao1';
daq = tfp.hardware.MockDAQ();
daq.initialize(struct('sampleRate', 10000, 'analogOutChannels', [0 1 3]));

config.laser = struct( ...
    'carbide_modulator_ao_channel', aoChannel, ...
    'carbide_voltage_min', 0, ...
    'carbide_voltage_max', 5, ...
    'arm_transmission',    0.182);

laser = tfp.hardware.LaserPowerController(daq, config, struct( ...
    'confirmFcn', confirmFcn, 'laserState', laserState));

meter = tfp.sim.SyntheticPowerMeter(daq, aoChannel, ...
    struct('maxMw', maxMw, 'noiseMw', noiseMw));

curve = tfp.calibration.powerMeterSweepSingle(laser, struct( ...
    'voltageSteps', voltageSteps, ...
    'meter',        meter, ...
    'patterns',     patterns, ...
    'settleTimeS',  0, ...
    'warmupTimeS',  0, ...
    'readPauseS',   0, ...
    'nAverages',    3, ...
    'verbose',      false, ...
    'notes',        'synthetic meter (powerMeterSweepSingle_mock)'));

truth = struct( ...
    'responseFcn',  meter.responseFcn, ...
    'voltageSteps', voltageSteps, ...
    'expectedMw',   arrayfun(meter.responseFcn, voltageSteps), ...
    'aoChannel',    aoChannel, ...
    'daq',          daq, ...
    'laser',        laser, ...
    'meter',        meter);
end
