function sys = specToSys(spec)
%specToSys Convert a validated mask spec to a computeDefocusMask sys struct.
%
%   sys = tfp.slm.specToSys(spec)
%
%   Used on the SLM-PC side (slm_server) to rebuild the exact sys the DAQ
%   PC used, guaranteeing both ends compute identical masks.

tfp.slm.validateSpec(spec);
sys = struct( ...
    'nRows',        spec.nRows, ...
    'nCols',        spec.nCols, ...
    'pitchXUm',     spec.pitchXUm, ...
    'pitchYUm',     spec.pitchYUm, ...
    'nStates',      spec.nStates, ...
    'lambdaNm',     spec.lambdaNm, ...
    'mRelay',       spec.mRelay, ...
    'nImm',         spec.nImm, ...
    'fObjUm',       spec.fObjUm, ...
    'NA',           spec.NA, ...
    'wrapPhaseRad', spec.wrapPhaseRad);
end
