classdef test_optics_handoff_constants < matlab.unittest.TestCase
    %test_optics_handoff_constants The cross-repo drift tripwire.
    %   docs/optics_handoff.md is generated by the optics model (sibling
    %   repo `TF optics simulator`, `python -m configs.dmd_handoff`) and
    %   carries a machine-readable constants block. This test asserts this
    %   repo's own hardware constants against that block, so a number that
    %   moves in the model (or is mistyped here) becomes a red test rather
    %   than a discovery on the rig.
    %
    %   History that motivates it: the two repos held wavelength 1030 vs
    %   1038 nm for months (1030 is the CARBIDE's front-panel SETPOINT;
    %   the factory test certificate measures 1038, and even the current
    %   rig's FS-50 runs ~1040 — see run_powerMeterSweep.m). Nothing
    %   caught it because nothing compared them.

    methods (Test)

        function the_handoff_parses_and_names_the_merged_arm(testCase)
            c = tfp.util.readHandoffConstants('reload');
            testCase.verifyGreaterThanOrEqual(c.handoff_rev, 4, ...
                'rev < 4 predates the merged arm and the constants block');
            testCase.verifyEqual(c.build, 'merged_arm', ...
                ['the design-intent keys are only valid for the merged ' ...
                 'arm; a different build string means this test''s ' ...
                 'assumptions no longer hold']);
        end

        function plm_driver_geometry_matches_the_handoff(testCase)
            c = tfp.util.readHandoffConstants();
            plm = tfp.hardware.DLPC900_PLM(struct());
            testCase.verifyEqual(plm.nCols,        c.plm_cols);
            testCase.verifyEqual(plm.nRows,        c.plm_rows);
            testCase.verifyEqual(plm.pitchX_um,    c.plm_pitch_disp_um);
            testCase.verifyEqual(plm.pitchY_um,    c.plm_pitch_cross_um);
            testCase.verifyEqual(plm.nPhaseStates, c.plm_phase_states);
        end

        function plm_wavelength_matches_the_measured_cert_value(testCase)
            % 1038 nm is MEASURED [CERT s/n C264570], not the 1030 nm
            % setpoint. The driver default must track the handoff; a rig
            % running the FS-50 (~1040 nm) overrides via config, it does
            % not edit the default back.
            c = tfp.util.readHandoffConstants();
            plm = tfp.hardware.DLPC900_PLM(struct());
            testCase.verifyEqual(plm.lambda_nm, c.wavelength_nm);
        end

        function mock_dmd_defaults_match_the_handoff_geometry(testCase)
            c = tfp.util.readHandoffConstants();
            dmd = tfp.hardware.MockDMD();
            dmd.initialize(struct());
            testCase.verifyEqual(dmd.nRows,          c.dmd_rows);
            testCase.verifyEqual(dmd.nCols,          c.dmd_cols);
            testCase.verifyEqual(dmd.maxPatternRate, c.dmd_binary_rate_hz);
        end

        function real_dmd_driver_source_matches_the_handoff(testCase)
            % DLP650LNIR_DMD hardcodes its geometry inside initialize()'s
            % switch and cannot be instantiated without the ALP DLL, so
            % the source text is checked directly. Crude, but a mistyped
            % constant in that switch is exactly the drift this tripwire
            % exists to catch.
            c = tfp.util.readHandoffConstants();
            testsDir = fileparts(mfilename('fullpath'));
            srcFile  = fullfile(fileparts(testsDir), 'src', '+tfp', ...
                '+hardware', 'DLP650LNIR_DMD.m');
            src = fileread(srcFile);
            blk = regexp(src, 'case ''4\.3''(.*?)case ''4\.1''', ...
                'tokens', 'once');
            testCase.assertNotEmpty(blk, ...
                'could not find the ''4.3''/DLP650LNIR switch block');
            grab = @(name) str2double(regexp(blk{1}, ...
                ['obj\.' name '\s*=\s*(\d+)'], 'tokens', 'once'));
            testCase.verifyEqual(grab('nRows'),          c.dmd_rows);
            testCase.verifyEqual(grab('nCols'),          c.dmd_cols);
            testCase.verifyEqual(grab('maxPatternRate'), c.dmd_binary_rate_hz);
        end

        function the_safety_caps_are_present_and_sane(testCase)
            % on_fraction_cap is ENFORCED by tfp.hardware.DMD
            % .assertPatternsSafe, which reads it from this block — so its
            % presence and value are a safety property, not bookkeeping.
            c = tfp.util.readHandoffConstants();
            testCase.verifyEqual(c.on_fraction_cap, 0.50, ...
                'the agreed cap is 50% (optics_handoff.md §7)');
            testCase.verifyGreaterThan(c.slm_alignment_cap_mW, 0);
            testCase.verifyLessThan(c.slm_alignment_cap_mW, 1000, ...
                'an all-ON alignment cap near a watt would mean the SLM line-focus model changed radically — re-read §7b before trusting it');
        end

    end
end
