classdef test_dmd_on_fraction_cap < matlab.unittest.TestCase
    %test_dmd_on_fraction_cap The 50% ON-fraction safety cap on uploads.
    %   docs/optics_handoff.md §7 (generated by the optics model): a
    %   contiguous ON region focuses the whole pulse at the first relay's
    %   pupil, and the intensity there scales as the SQUARE of the ON
    %   fraction — the all-ON alignment frame at full laser power crosses
    %   the air-ionisation threshold. The cap must hold at any laser power,
    %   so tfp.hardware.DMD.assertPatternsSafe enforces it on every
    %   loadPatternSequence, mock included. These tests pin that behavior.

    methods (Access = private)
        function dmd = freshMock(~)
            dmd = tfp.hardware.MockDMD();
            dmd.initialize(struct('loadLatencyMsPerPattern', 0));
        end

        function p = patternWithOnRows(~, dmd, nOnRows)
            p = false(dmd.nRows, dmd.nCols);
            p(1:nOnRows, :) = true;
        end
    end

    methods (Test)

        function a_sixty_percent_frame_is_refused(testCase)
            dmd = testCase.freshMock();
            p = testCase.patternWithOnRows(dmd, round(0.6 * dmd.nRows));
            opts = struct('exposureUs', 100, 'darkTimeUs', 0);
            testCase.verifyError( ...
                @() dmd.loadPatternSequence(p, opts), ...
                'tfp:hardware:DMD:onFractionExceeded');
        end

        function the_all_on_alignment_frame_is_refused(testCase)
            % The named dangerous case in the handoff: alignment, all ON.
            dmd = testCase.freshMock();
            p = true(dmd.nRows, dmd.nCols);
            opts = struct('exposureUs', 100, 'darkTimeUs', 0);
            testCase.verifyError( ...
                @() dmd.loadPatternSequence(p, opts), ...
                'tfp:hardware:DMD:onFractionExceeded');
        end

        function one_bad_frame_in_a_stack_is_enough_to_refuse(testCase)
            dmd = testCase.freshMock();
            good = testCase.patternWithOnRows(dmd, round(0.1 * dmd.nRows));
            bad  = testCase.patternWithOnRows(dmd, round(0.8 * dmd.nRows));
            opts = struct('exposureUs', 100, 'darkTimeUs', 0);
            testCase.verifyError( ...
                @() dmd.loadPatternSequence(cat(3, good, bad), opts), ...
                'tfp:hardware:DMD:onFractionExceeded');
        end

        function a_forty_percent_frame_loads(testCase)
            dmd = testCase.freshMock();
            p = testCase.patternWithOnRows(dmd, round(0.4 * dmd.nRows));
            opts = struct('exposureUs', 100, 'darkTimeUs', 0);
            dmd.loadPatternSequence(p, opts);   % must not throw
            st = dmd.getStatus();
            testCase.verifyTrue(isstruct(st), ...
                'the sequence should have loaded normally');
        end

        function exactly_half_on_is_the_boundary_and_loads(testCase)
            % The rule is "never MORE than 50%": exactly half is legal.
            dmd = testCase.freshMock();
            p = testCase.patternWithOnRows(dmd, dmd.nRows / 2);
            opts = struct('exposureUs', 100, 'darkTimeUs', 0);
            dmd.loadPatternSequence(p, opts);   % must not throw
        end

        function the_cap_comes_from_the_handoff_not_from_code(testCase)
            % assertPatternsSafe reads on_fraction_cap from the generated
            % handoff; this pins the plumbing so a hardcoded copy cannot
            % sneak back in unnoticed if the handoff value ever moves.
            c = tfp.util.readHandoffConstants();
            testCase.verifyEqual(c.on_fraction_cap, 0.50);
        end

    end
end
