function result = exp_ensemble_fill_factor_power(dmd, daq, roiCentroids_scan, calib, options)
%exp_ensemble_fill_factor_power Ensemble photostim with fill-factor power modulation.
%
%   Two conditions, run back-to-back, with interleaved trial order within
%   each condition. Per-neuron power is set by the fraction of pixels in
%   that neuron's DMD disk that are ON. The FS-50 AO voltage is held
%   constant — all power modulation is DMD-side. Every trial gets an
%   independent random pixel draw (fresh subset), even at the same fill
%   fraction.
%
%   Condition 1 — Uniform sweep
%     All cells driven at the same fill fraction. Step through K levels
%     (default 0.1:0.1:1.0) with M repeats per level (default 10).
%     Default: 10 levels * 10 repeats = 100 trials, shuffled.
%
%   Condition 2 — Differential per-cell fills
%     Each cell drawn independently from a discrete set
%     (default {0.2, 0.4, 0.6, 0.8, 1.0}). D distributions are generated by
%     rejection-sampling until all pairwise Pearson |r| <= maxCorr
%     (default 0.15 across 3 distributions). Each distribution is repeated
%     M times (default 10). Default: 3 dists * 10 repeats = 30 trials,
%     shuffled.
%
%   result = exp_ensemble_fill_factor_power(dmd, daq, roiCentroids_scan, calib)
%   result = exp_ensemble_fill_factor_power(dmd, daq, roiCentroids_scan, calib, options)
%
%   Inputs:
%     dmd               - tfp.hardware.DMD subclass (MockDMD or real).
%     daq               - tfp.hardware.DAQ subclass (MockDAQ or real).
%     roiCentroids_scan - N x 2 double, [x y] centroids in ScanImage
%                         scan-field coordinates.
%     calib             - Calibration struct with .dmdToScan_affine (3x3).
%
%   options (all optional):
%     Shared:
%       .radiusPx              - Disk radius per neuron in DMD px (default 15).
%       .stimDurationS         - Laser ON per trial (default 0.5 s).
%       .interStimS            - ISI between trials (default 3.0 s).
%       .aoChannel             - AO channel for laser (default 'ao1').
%       .powerV                - Fixed AO voltage during stim (default 5.0).
%       .rngSeed               - Master RNG seed (default 0).
%       .showLiveFigure        - Show live DMD figure (default true).
%       .sessionDir            - Session log dir (default '').
%       .exposureUs            - DMD per-frame exposure (default 5000).
%       .darkTimeUs            - DMD dark time (default 0).
%
%     Condition 1 (uniform sweep):
%       .runUniform            - Enable condition 1 (default true).
%       .uniformFillFractions  - 1 x K vector in [0, 1] (default 0.1:0.1:1.0).
%       .uniformNRepeats       - Repeats per level (default 10).
%
%     Condition 2 (differential):
%       .runDifferential       - Enable condition 2 (default true).
%       .differentialNDistributions - Number of distributions (default 3).
%       .differentialNRepeats  - Repeats per distribution (default 10).
%       .differentialFillSet   - Discrete fill values to draw from per cell
%                                (default [0.2 0.4 0.6 0.8 1.0]).
%       .differentialMaxCorr   - Max pairwise |Pearson r| accepted across
%                                the D distributions (default 0.15).
%       .differentialMaxAttempts - Rejection-sampling attempts before
%                                falling back to best-found (default 20000).
%
%   Output result struct includes per-condition trial logs, the realised
%   distributions (with achieved pairwise correlations), the run order, and
%   per-trial achieved ON-pixel counts.
%
%   See also tfp.patterns.fillFactorEnsemble.

if nargin < 5 || isempty(options)
    options = struct();
end

% --- Shared options ---
radiusPx       = configField(options, 'radiusPx',       15);
stimDurationS  = configField(options, 'stimDurationS',  0.5);
interStimS     = configField(options, 'interStimS',     3.0);
aoChannel      = configField(options, 'aoChannel',      'ao1');
powerV         = configField(options, 'powerV',         5.0);
rngSeed        = configField(options, 'rngSeed',        0);
showLiveFigure = configField(options, 'showLiveFigure', true);
sessionDir     = configField(options, 'sessionDir',     '');
exposureUs     = configField(options, 'exposureUs',     5000);
darkTimeUs     = configField(options, 'darkTimeUs',     0);

% --- Condition 1 options ---
runUniform           = configField(options, 'runUniform',           true);
uniformFillFractions = configField(options, 'uniformFillFractions', 0.1:0.1:1.0);
uniformNRepeats      = configField(options, 'uniformNRepeats',      10);

% --- Condition 2 options ---
runDifferential          = configField(options, 'runDifferential',          true);
diffNDistributions       = configField(options, 'differentialNDistributions', 3);
diffNRepeats             = configField(options, 'differentialNRepeats',     10);
diffFillSet              = configField(options, 'differentialFillSet',      [0.2 0.4 0.6 0.8 1.0]);
diffMaxCorr              = configField(options, 'differentialMaxCorr',      0.15);
diffMaxAttempts          = configField(options, 'differentialMaxAttempts',  20000);

% --- Validate ROI input ---
if ~isnumeric(roiCentroids_scan) || ndims(roiCentroids_scan) ~= 2 ...
        || size(roiCentroids_scan, 2) ~= 2 || size(roiCentroids_scan, 1) < 1
    error('tfp:experiments:exp_ensemble_fill_factor_power:badROIs', ...
        'roiCentroids_scan must be Nx2 with N >= 1.');
end
if ~isstruct(calib) || ~isfield(calib, 'dmdToScan_affine')
    error('tfp:experiments:exp_ensemble_fill_factor_power:badCalib', ...
        'calib must be a struct with field .dmdToScan_affine (3x3).');
end

uniformFillFractions = uniformFillFractions(:)';
if runUniform
    if any(~isfinite(uniformFillFractions)) ...
            || any(uniformFillFractions < 0) || any(uniformFillFractions > 1)
        error('tfp:experiments:exp_ensemble_fill_factor_power:badFractions', ...
            'uniformFillFractions entries must be finite values in [0, 1].');
    end
end

diffFillSet = diffFillSet(:)';
if runDifferential
    if isempty(diffFillSet) || any(~isfinite(diffFillSet)) ...
            || any(diffFillSet < 0) || any(diffFillSet > 1)
        error('tfp:experiments:exp_ensemble_fill_factor_power:badDiffSet', ...
            'differentialFillSet must be a non-empty vector of values in [0, 1].');
    end
end

nROIs = size(roiCentroids_scan, 1);

% --- Coordinate transform: scan-field -> DMD pixels ---
dmdCentroids = scanFieldToDMD(roiCentroids_scan, calib);
dmdCentroids = clampToDMD(dmdCentroids, dmd, roiCentroids_scan);

% Seed the master RNG once — every fillFactorEnsemble call below uses
% rngSeed=[] so the same RNG stream is consumed in sequence (reproducible
% from rngSeed alone).
rng(rngSeed);

% =========================================================================
% Build trial lists
% =========================================================================

% --- Condition 1 trials ---
c1 = struct();
if runUniform
    nLevels1 = numel(uniformFillFractions);
    c1.nTrials       = nLevels1 * uniformNRepeats;
    c1.fillPerCell   = zeros(nROIs, c1.nTrials);
    c1.levelIdx      = zeros(1, c1.nTrials);
    c1.fillFraction  = zeros(1, c1.nTrials);
    c1.repeatIdx     = zeros(1, c1.nTrials);
    t = 0;
    for k = 1:nLevels1
        for rep = 1:uniformNRepeats
            t = t + 1;
            c1.fillPerCell(:, t) = uniformFillFractions(k);
            c1.fillFraction(t)   = uniformFillFractions(k);
            c1.levelIdx(t)       = k;
            c1.repeatIdx(t)      = rep;
        end
    end
    c1.fillFractions = uniformFillFractions;
    c1.nLevels       = nLevels1;
    c1.nRepeats      = uniformNRepeats;
else
    c1.nTrials = 0;
end

% --- Condition 2 distributions + trials ---
c2 = struct();
if runDifferential
    [c2.distributions, c2.pairwiseCorr, c2.attempts, c2.fallback] = ...
        drawDecorrelatedDistributions( ...
            nROIs, diffNDistributions, diffFillSet, ...
            diffMaxCorr, diffMaxAttempts);

    c2.nTrials       = diffNDistributions * diffNRepeats;
    c2.fillPerCell   = zeros(nROIs, c2.nTrials);
    c2.distIdx       = zeros(1, c2.nTrials);
    c2.repeatIdx     = zeros(1, c2.nTrials);
    t = 0;
    for d = 1:diffNDistributions
        for rep = 1:diffNRepeats
            t = t + 1;
            c2.fillPerCell(:, t) = c2.distributions(:, d);
            c2.distIdx(t)        = d;
            c2.repeatIdx(t)      = rep;
        end
    end
    c2.fillSet         = diffFillSet;
    c2.nDistributions  = diffNDistributions;
    c2.nRepeats        = diffNRepeats;
    c2.maxCorrAccepted = diffMaxCorr;
else
    c2.nTrials = 0;
end

nTotal = c1.nTrials + c2.nTrials;
if nTotal == 0
    error('tfp:experiments:exp_ensemble_fill_factor_power:noTrials', ...
        'Both conditions are disabled — nothing to run.');
end

% =========================================================================
% Build pattern stack — fresh random draw per trial
% =========================================================================
fprintf('[fill_factor_power] Building %d DMD patterns (cond1=%d, cond2=%d) ', ...
    nTotal, c1.nTrials, c2.nTrials);
fprintf('for %d ROIs, disk r=%g px (~%d px/neuron)...\n', ...
    nROIs, radiusPx, round(pi * radiusPx^2));

patternStack = false(dmd.nRows, dmd.nCols, nTotal);
ffOpts = struct('permutations', {{}}, 'rngSeed', []);   % use already-seeded RNG

c1.nOnPixels = zeros(nROIs, c1.nTrials);
c2.nOnPixels = zeros(nROIs, c2.nTrials);
nPatchPixels = [];

patIdx = 0;
% Condition 1 patterns: build in (level, repeat) order; pattern index t in
% the stack matches c1 trial t.
for t = 1:c1.nTrials
    patIdx = patIdx + 1;
    [pat, info] = tfp.patterns.fillFactorEnsemble( ...
        dmd, dmdCentroids, radiusPx, c1.fillPerCell(:, t), ffOpts);
    patternStack(:, :, patIdx) = pat;
    c1.nOnPixels(:, t) = info.nOnPixels;
    if isempty(nPatchPixels)
        nPatchPixels = info.nPatchPixels;
    end
end

% Condition 2 patterns: stack index = c1.nTrials + t.
for t = 1:c2.nTrials
    patIdx = patIdx + 1;
    [pat, info] = tfp.patterns.fillFactorEnsemble( ...
        dmd, dmdCentroids, radiusPx, c2.fillPerCell(:, t), ffOpts);
    patternStack(:, :, patIdx) = pat;
    c2.nOnPixels(:, t) = info.nOnPixels;
    if isempty(nPatchPixels)
        nPatchPixels = info.nPatchPixels;
    end
end

% =========================================================================
% Interleave within each condition
% =========================================================================
if c1.nTrials > 0
    c1.runOrder = randperm(c1.nTrials);                       % indices into c1 columns
    c1.stackIdx = c1.runOrder;                                % matches pattern stack
end
if c2.nTrials > 0
    c2.runOrder = randperm(c2.nTrials);                       % indices into c2 columns
    c2.stackIdx = c1.nTrials + c2.runOrder;                   % stack offset by cond1
end

% =========================================================================
% Load onto DMD
% =========================================================================
dmdSeqOpts.exposureUs = exposureUs;
dmdSeqOpts.darkTimeUs = darkTimeUs;
dmd.loadPatternSequence(patternStack, dmdSeqOpts);
dmd.armSequence();

% --- Live figure ---
if showLiveFigure
    lh = initLiveFigure(dmd.nRows, dmd.nCols, dmdCentroids, radiusPx);
else
    lh = [];
end

% Safety: laser starts off + ensured off on cleanup.
daq.outputSingleAnalog(aoChannel, 0);
cleanupLaser = onCleanup(@() safetyOff(daq, aoChannel));  %#ok<NASGU>

% =========================================================================
% Run condition 1
% =========================================================================
if runUniform
    fprintf('\n=== COND 1: UNIFORM SWEEP (%d trials = %d levels x %d reps, %.3f V, %.0f ms ON / %.1f s ISI, shuffled) ===\n', ...
        c1.nTrials, c1.nLevels, c1.nRepeats, powerV, stimDurationS*1e3, interStimS);

    for k = 1:c1.nTrials
        t       = c1.runOrder(k);     % column index into c1
        sIdx    = c1.stackIdx(k);     % pattern stack index
        fill    = c1.fillFraction(t);
        rep     = c1.repeatIdx(t);
        lvl     = c1.levelIdx(t);

        dmd.advanceToPattern(sIdx);
        updateFigure(lh, patternStack(:,:,sIdx), dmdCentroids, ...
            c1.fillPerCell(:, t), ...
            sprintf('Cond 1  trial %d/%d  —  %.0f%% fill  —  rep %d/%d (level %d/%d)  ON', ...
                k, c1.nTrials, fill*100, rep, c1.nRepeats, lvl, c1.nLevels), ...
            false);    % no per-cell labels in cond 1 (all cells same)

        daq.outputSingleAnalog(aoChannel, powerV);
        pause(stimDurationS);
        daq.outputSingleAnalog(aoChannel, 0);

        updateFigure(lh, patternStack(:,:,sIdx), dmdCentroids, ...
            c1.fillPerCell(:, t), ...
            sprintf('Cond 1  trial %d/%d  —  %.0f%% fill  —  off', ...
                k, c1.nTrials, fill*100), false);

        pause(interStimS);

        if mod(k, 10) == 0 || k == c1.nTrials
            fprintf('  [cond1] %d/%d done\n', k, c1.nTrials);
        end
    end
end

% =========================================================================
% Run condition 2
% =========================================================================
if runDifferential
    cstr = corrPrintStr(c2.pairwiseCorr);
    fprintf('\n=== COND 2: DIFFERENTIAL (%d trials = %d dists x %d reps, max |r|=%.3f %s) ===\n', ...
        c2.nTrials, c2.nDistributions, c2.nRepeats, max(abs(c2.pairwiseCorr)), cstr);
    if c2.fallback
        fprintf('  [cond2] WARNING: decorrelation threshold not met in %d attempts; using best.\n', c2.attempts);
    end

    for k = 1:c2.nTrials
        t    = c2.runOrder(k);
        sIdx = c2.stackIdx(k);
        d    = c2.distIdx(t);
        rep  = c2.repeatIdx(t);

        dmd.advanceToPattern(sIdx);
        updateFigure(lh, patternStack(:,:,sIdx), dmdCentroids, ...
            c2.fillPerCell(:, t), ...
            sprintf('Cond 2  trial %d/%d  —  dist %d/%d  rep %d/%d  ON', ...
                k, c2.nTrials, d, c2.nDistributions, rep, c2.nRepeats), ...
            true);    % show per-cell fill labels

        daq.outputSingleAnalog(aoChannel, powerV);
        pause(stimDurationS);
        daq.outputSingleAnalog(aoChannel, 0);

        updateFigure(lh, patternStack(:,:,sIdx), dmdCentroids, ...
            c2.fillPerCell(:, t), ...
            sprintf('Cond 2  trial %d/%d  —  dist %d/%d  rep %d/%d  off', ...
                k, c2.nTrials, d, c2.nDistributions, rep, c2.nRepeats), ...
            true);

        pause(interStimS);

        if mod(k, 5) == 0 || k == c2.nTrials
            fprintf('  [cond2] %d/%d done\n', k, c2.nTrials);
        end
    end
end

% =========================================================================
% Log + return
% =========================================================================
if ~isempty(sessionDir) && isfolder(sessionDir)
    tfp.io.sessionLog(sessionDir, 'fill-factor-power-complete', struct( ...
        'nROIs', nROIs, 'radiusPx', radiusPx, ...
        'cond1Trials', c1.nTrials, 'cond2Trials', c2.nTrials, ...
        'powerV', powerV, ...
        'stimDurationS', stimDurationS, 'interStimS', interStimS, ...
        'rngSeed', rngSeed));
end

result.nROIs          = nROIs;
result.radiusPx       = radiusPx;
result.dmdCentroids   = dmdCentroids;
result.nPatchPixels   = nPatchPixels;
result.powerV         = powerV;
result.stimDurationS  = stimDurationS;
result.interStimS     = interStimS;
result.rngSeed        = rngSeed;
result.condition1     = c1;
result.condition2     = c2;
result.completedAt    = datetime('now');

fprintf('\n[fill_factor_power] Complete: cond1=%d trials, cond2=%d trials.\n', ...
    c1.nTrials, c2.nTrials);
end

% =========================================================================
% Decorrelated-distribution sampler
% =========================================================================

function [bestDists, bestPairwise, attemptsUsed, fallback] = ...
    drawDecorrelatedDistributions(nCells, nDists, fillSet, maxCorr, maxAttempts)
%drawDecorrelatedDistributions Rejection-sample D fill-fraction vectors.
%
%   Returns the first triple whose pairwise |Pearson r| values are all
%   <= maxCorr. If no such triple is found within maxAttempts, returns the
%   best (lowest max |r|) attempt and sets fallback = true.

nFill = numel(fillSet);
fillSet = fillSet(:)';
triuMask = triu(true(nDists), 1);
nPairs   = sum(triuMask(:));

bestPairwise = nan(nPairs, 1);
bestMaxAbs   = inf;
bestDists    = [];
attemptsUsed = 0;
fallback     = true;

for attempt = 1:maxAttempts
    attemptsUsed = attempt;
    % Each cell picks independently from fillSet for each of the D distributions
    candidate = fillSet(randi(nFill, nCells, nDists));   % nCells x nDists

    % Reject any candidate where a column is constant — Pearson r is NaN
    if any(std(candidate, 0, 1) == 0)
        continue
    end

    C = corr(candidate);
    pairs = C(triuMask);
    maxAbs = max(abs(pairs));

    if maxAbs < bestMaxAbs
        bestMaxAbs   = maxAbs;
        bestDists    = candidate;
        bestPairwise = pairs;
    end
    if maxAbs <= maxCorr
        fallback = false;
        return
    end
end

if isempty(bestDists)
    error('tfp:experiments:exp_ensemble_fill_factor_power:noViableDist', ...
        'Could not draw any non-constant distributions in %d attempts.', maxAttempts);
end

warning('tfp:experiments:exp_ensemble_fill_factor_power:decorrFallback', ...
    'No %d-tuple with max |r| <= %.3f found in %d attempts; using best (max |r| = %.3f).', ...
    nDists, maxCorr, maxAttempts, bestMaxAbs);
end

function s = corrPrintStr(corrs)
parts = arrayfun(@(x) sprintf('%+.3f', x), corrs, 'UniformOutput', false);
s = ['pairs=[', strjoin(parts, ' '), ']'];
end

% =========================================================================
% Coordinate transform
% =========================================================================

function dmdCoords = scanFieldToDMD(scanCoords, calib)
scanToDmd = inv(calib.dmdToScan_affine);
nPts  = size(scanCoords, 1);
pts_h = [scanCoords, ones(nPts, 1)]';
dmd_h = scanToDmd * pts_h;
dmdCoords = dmd_h(1:2, :)';
end

function dmdCoords = clampToDMD(dmdCoords, dmd, scanCoords)
nPts = size(dmdCoords, 1);
for k = 1:nPts
    col = dmdCoords(k, 1);
    row = dmdCoords(k, 2);
    if col < 1 || col > dmd.nCols || row < 1 || row > dmd.nRows
        warning('tfp:experiments:exp_ensemble_fill_factor_power:roiOutOfBounds', ...
            'ROI %d at scan-field [%.1f %.1f] maps to DMD [%.1f %.1f], outside [1..%d, 1..%d]. Clamping.', ...
            k, scanCoords(k,1), scanCoords(k,2), col, row, dmd.nCols, dmd.nRows);
        dmdCoords(k, 1) = max(1, min(dmd.nCols, col));
        dmdCoords(k, 2) = max(1, min(dmd.nRows, row));
    end
end
end

% =========================================================================
% Live figure
% =========================================================================

function lh = initLiveFigure(nRows, nCols, dmdCentroids, radiusPx)
lh.fig = figure('Name', 'Fill-Factor Power Sweep — Live DMD Pattern', ...
    'NumberTitle', 'off', 'Color', 'k', ...
    'Position', [80 80 960 640]);
lh.ax = axes(lh.fig, 'Color', 'k', ...
    'Position', [0.02 0.10 0.96 0.83]);

lh.img = imagesc(lh.ax, zeros(nRows, nCols));
colormap(lh.ax, gray);
clim(lh.ax, [0 1]);
axis(lh.ax, 'image');
axis(lh.ax, 'off');
hold(lh.ax, 'on');

lh.markersAll = plot(lh.ax, dmdCentroids(:,1), dmdCentroids(:,2), ...
    'o', 'Color', [0.4 0.4 0.4], 'MarkerSize', 18, ...
    'LineWidth', 1.5, 'MarkerFaceColor', 'none');

lh.markersActive = plot(lh.ax, dmdCentroids(:,1), dmdCentroids(:,2), 'ro', ...
    'MarkerSize', 18, 'LineWidth', 2.5, 'MarkerFaceColor', 'none');

% Per-cell text labels (shown only during cond 2). Pre-create one text
% handle per ROI so updates are fast.
nROIs = size(dmdCentroids, 1);
lh.cellLabels = gobjects(nROIs, 1);
for k = 1:nROIs
    lh.cellLabels(k) = text(lh.ax, ...
        dmdCentroids(k,1) + radiusPx + 8, dmdCentroids(k,2), '', ...
        'Color', 'y', 'FontSize', 10, 'FontWeight', 'bold');
end

lh.titleTxt = title(lh.ax, 'Loading patterns...', ...
    'Color', 'w', 'FontSize', 13, 'FontWeight', 'bold');
drawnow;
end

function updateFigure(lh, pattern, dmdCentroids, fillPerCell, titleStr, showCellLabels)
if isempty(lh)
    return
end
set(lh.img, 'CData', double(pattern));
if showCellLabels
    for k = 1:numel(lh.cellLabels)
        set(lh.cellLabels(k), 'String', sprintf('%.0f%%', fillPerCell(k) * 100));
    end
else
    for k = 1:numel(lh.cellLabels)
        set(lh.cellLabels(k), 'String', '');
    end
end
set(lh.titleTxt, 'String', titleStr);
drawnow limitrate;
end

% =========================================================================
% Cleanup / helpers
% =========================================================================

function safetyOff(daq, aoChannel)
try
    daq.outputSingleAnalog(aoChannel, 0);
catch
end
end

function value = configField(s, name, default)
if isfield(s, name)
    value = s.(name);
else
    value = default;
end
end
