classdef DMD < handle
    %DMD Abstract interface for DMD pattern projectors.
    %   Subclasses include MockDMD (simulator) and DLP650LNIR_DMD (real
    %   hardware via ViALUX ALP-4.3). Experiment code talks to this
    %   interface, never to a concrete class.

    properties (Abstract, SetAccess = protected)
        nRows           % e.g., 800 for DLP650LNIR
        nCols           % e.g., 1280
        maxPatternRate  % Hz, binary patterns
        isInitialized
    end

    methods (Abstract)
        initialize(obj, config)

        % patterns: logical(nRows, nCols, nPatterns)
        % options: struct with .exposureUs, .darkTimeUs, .triggerMode
        loadPatternSequence(obj, patterns, options)

        armSequence(obj)
        softTrigger(obj)
        advanceToPattern(obj, idx)
        status = getStatus(obj)
        cleanup(obj)
    end

    methods
        function pxCount = activePixelCount(obj, patternIdx)
            % Useful for power-per-target calculations
            error('not implemented');
        end

        function assertPatternsSafe(obj, patterns) %#ok<INUSL>
            %assertPatternsSafe Refuse any frame that lights too much chip.
            %   THE RULE (docs/optics_handoff.md §7, generated by the
            %   optics model): never illuminate more than on_fraction_cap
            %   (50%) of the mirrors. Every 4f relay of the DMD forms a
            %   real focus in air at its pupil; the intensity there scales
            %   as the SQUARE of the ON fraction, and the all-ON alignment
            %   frame at full laser power crosses the air-ionisation
            %   threshold. The cap must hold at ANY laser power, because
            %   the power knob is independent of the pattern — so it is
            %   enforced here, on every upload path, not left to operator
            %   discipline. One nnz per frame; costs nothing.
            %
            %   The cap is read from the handoff, not hardcoded, so the
            %   optics model stays the single source of the number. A
            %   missing handoff file is an error (fail closed).
            caps = tfp.util.readHandoffConstants();
            cap  = caps.on_fraction_cap;
            for k = 1:size(patterns, 3)
                frame = patterns(:, :, k);
                frac  = nnz(frame) / numel(frame);
                if frac > cap
                    error('tfp:hardware:DMD:onFractionExceeded', ...
                        ['pattern %d lights %.0f%% of the chip; the cap ' ...
                         'is %.0f%% (docs/optics_handoff.md §7 — air ' ...
                         'breakdown at the relay pupil). Use a sparser ' ...
                         'pattern, and drop the laser power for any ' ...
                         'large solid region.'], k, 100 * frac, 100 * cap);
                end
            end
        end
    end
end
