function c = readHandoffConstants(mode)
%readHandoffConstants Parse the machine-readable optics-handoff constants.
%   c = tfp.util.readHandoffConstants() returns a struct with one field per
%   key of the fenced ```handoff-constants block in docs/optics_handoff.md.
%   Values that parse as numbers come back as doubles; everything else as
%   char.
%
%   docs/optics_handoff.md is GENERATED by the optics model (sibling repo
%   `TF optics simulator`, `python -m configs.dmd_handoff`) — never edit it
%   by hand here. This parser and the generator's parse_constants_block()
%   implement the same contract (flat `key: value` lines, `#` to end of
%   line is comment, blank lines ignored); change them together.
%
%   Two kinds of keys, per the document's own grouping:
%     * device geometry — build-independent hardware facts. Asserted
%       against this repo's hardware classes by
%       tests/test_optics_handoff_constants.m (the cross-repo tripwire).
%     * merged-arm design intent + safety caps — valid for the future
%       merged arm; NOT a calibration for the current FS-50 rig. The
%       safety caps (on_fraction_cap above all) are enforced regardless:
%       tfp.hardware.DMD.assertPatternsSafe reads its cap from here.
%
%   The parsed struct is cached for the MATLAB session; call
%   tfp.util.readHandoffConstants('reload') after regenerating the file.

persistent cached
if nargin >= 1 && strcmpi(char(mode), 'reload')
    cached = [];
end
if ~isempty(cached)
    c = cached;
    return;
end

% repo root = three package levels up from src/+tfp/+util/
utilDir  = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(fileparts(utilDir)));
mdPath   = fullfile(repoRoot, 'docs', 'optics_handoff.md');
if ~isfile(mdPath)
    error('tfp:util:readHandoffConstants:fileNotFound', ...
        ['%s not found. It is generated by the sibling ' ...
         '`TF optics simulator` repo (`python -m configs.dmd_handoff`) ' ...
         'and committed here; a missing handoff means safety caps ' ...
         'cannot be read, so this is an error, not a warning.'], mdPath);
end

raw = fileread(mdPath);
raw = raw(raw ~= char(13));                     % tolerate CRLF checkouts

blk = regexp(raw, '```handoff-constants\n(.*?)```', 'tokens', 'once');
if isempty(blk)
    error('tfp:util:readHandoffConstants:noBlock', ...
        'no ```handoff-constants block in %s.', mdPath);
end

c = struct();
lines = strsplit(blk{1}, char(10));
for i = 1:numel(lines)
    line = lines{i};
    hash = strfind(line, '#');
    if ~isempty(hash)
        line = line(1:hash(1) - 1);
    end
    line = strtrim(line);
    if isempty(line)
        continue;
    end
    colon = strfind(line, ':');
    if isempty(colon)
        error('tfp:util:readHandoffConstants:badLine', ...
            'constants line without a colon in %s: ''%s''.', mdPath, line);
    end
    key = strtrim(line(1:colon(1) - 1));
    val = strtrim(line(colon(1) + 1:end));
    num = str2double(val);
    if ~isnan(num)
        c.(key) = num;
    else
        c.(key) = val;
    end
end

cached = c;
end
